insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (10680,'TNFDEV','ТН.КИС ЭХД', 'ehd' ) ;
insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (11880,'BUNKER','ТН.ЭАД','bunker' ) ;
insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (12180,'EATD','ТН.ЭАТД', 'eatd' ) ;
insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (13781,'TNUZDO','ТН. ЮЗДО', 'uzdo' ) ;
insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (13980,'TNFRAMEWOR','ТН. Платформа','ead' ) ;
insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (15680,'TNENONEC','ТН Энерго-1С: интеграция','ehd.1s' ) ;
insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (15780,'TNASU','ТН. АСУ Закупки', 'ead.dev.001' ) ;
insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (15781,'TNBDAD','ТН. БД АД', 'ad' ) ;
insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (15782,'TNBDVE','ТН. БД ВЭ','ve' ) ;
insert into tmp_cppo_stat_project (PID,PMNEM, PCode, SmallCode) values (16180,'TNBDMI','ТН.ЭАД МИ и ИНП','mi' ) ;
commit;

insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('aakbulatov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('aakhmetov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('aakhmetova@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('aaraslanov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('abalkov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('aberezov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('abikbulatov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('aborzov@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('abugaev@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('aburtseva@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('abyakovleva@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('achernyatyev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('adautov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('adudin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('agalimov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('agonsales@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('akhakimov@it.ru','Разработчик');
-- insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('akapustin@it.ru','Руководитель проекта');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('akhismatullin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('akhubbutdinov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('akiselev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('akochenev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('akolpakov@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('akulikov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('alang@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('aleontyev@it.ru','Разработчик');
-- insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('alevanov@it.ru','Руководитель проекта');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('alyubimov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ammatveeva@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('amukhametov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('anikolenko@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('anstepanov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('anuzhdin@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('apovalyaeva@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('apribytkov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('apushkarev@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('asayapova@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ashabalin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ashugurova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('asolynin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('astepanenko@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('atlyasheva@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('atokarev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ausov@it.ru','Разработчик');
-- insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('av_boyko@it.ru','Руководитель проекта');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('avgrigoryev@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('azametelsky@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('azhdankin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('d_milovanov','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('daleksandrova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('defimov@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('demec@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dibragimov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dkrotov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dkukhar@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dkurbangaliev@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dmakarov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dmulyukov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('drastegaev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dschukin@it.ru','Разработчик');
-- insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dsemenyuk@it.ru','Руководитель проекта');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dshakhovkin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dshalygin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dshibaev@it.ru','Разработчик');
-- insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dshpakov@it.ru','Руководитель проекта');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dsibagatulin@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dskvoznikov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dsmiryagin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dvegorov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dvysokikh@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('dyushenkov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('eaberkov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ebezdenezhnykh@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('edarintseva@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('eefimov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('egilmanov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ekazeev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ekotova@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ekuderov@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('emichin@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('emironov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('emurzakaev@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('enasyrova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('enigmatullin@it.ru','Тестировщик');
-- insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('esalimzhanova@it.ru','Руководитель проекта');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('etarakanov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('etlyaumbetova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('evanifatyeva@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ezelenkin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ggaliullina@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('gshakirova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ifedorov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('iganin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('iklimaeva@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ikomissarov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ikoscheev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('imikryakov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('imilienko@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('imironov@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('inigmatzyanov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('inikolaev@it.ru','Разработчик');
-- insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('irogalev@it.ru','Руководитель проекта');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ishagov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('isitdikov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('itsarkova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('iyakshigulov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('kaleksandrov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('kbeduganov@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('kbolelyy@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('kmarkov@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('kromanova@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('kstarikov@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('lbikaeva@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('lgilmutdinova@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('lnigmatullina@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('lsabangulova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('marslanov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('mdernovsky@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('mfayzullin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('mkarimov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('mlakeeva@it.ru','Администратор');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('mmetusova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('mpuzovik@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('mterentyev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('mutkin@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nbabanin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nbochkarev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('neegorova@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nefimenko@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nevsmirnova@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ngorguts@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nkozlova@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nkrymshamkhal@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nkukin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nmisnikova@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('npetrova@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('npetukhov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nshaludkina@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('nvolgushev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('oakhmetshina@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('oboltaev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ogorbatova@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ohard@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('oragafurova@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ptrofimov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ptsiber@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('pushakov@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rakhmetvaleev@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rbasyrov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rfayzrakhmanov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rganeev@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rkhakimova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rkulikov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rkurzanov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rmazitov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rmugattarov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rshershukov@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('rzigangirov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('schuchelov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('sgaleev@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('sgolovanova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('skhakhichev@it.ru','Разработчик');
-- insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('sloginova','Руководитель проекта');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('ssosedkin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('tkhaybullina@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('tkortova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('tnovikova@it.ru','Тестировщик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('tuzbekov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('tzolotkova@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('v_mitin','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('vkolodin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('vkovryga@it.ru','Аналитик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('vmandarov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('vmedvedkov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('vparfenov@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('vrogozin@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('vsavinykh@it.ru','Разработчик');
insert into tmp_cppo_user_role(USER_KEY,USER_ROLE) values ('vsolodilin@it.ru','Аналитик');
commit;

insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('ehd.tp.001', 19714,'1.50-FP7','Разработчик', 1224.00,'Planned');
insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('ehd.tp.001', 19714,'1.50-FP7','Аналитик', 293.00,'Planned');
insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('ehd.tp.001', 19714,'1.50-FP7','Тестировщик', 791.00,'Planned');

insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('ehd.tir.003', 19714,'1.50-FP7','Разработчик', 1797.12,'Planned');
insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('ehd.tir.003', 19714,'1.50-FP7','Аналитик', 1346.40,'Planned');
insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('ehd.tir.003', 19714,'1.50-FP7','Тестировщик', 1347.84,'Planned');
insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('ehd.tir.003', 19746,'1.50-FP8','Разработчик', 880.32,'Planned');
insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('ehd.tir.003', 19746,'1.50-FP8','Аналитик', 500.8,'Planned');
insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('ehd.tir.003', 19746,'1.50-FP8','Тестировщик', 668.84,'Planned');

insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('mi.dev.001', 19716,'1.1','Разработчик', 2024.00,'Planned');
insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('mi.dev.001', 19716,'1.1','Аналитик', 861.00,'Planned');
insert into tmp_cppo_PlanCode(ProjectCode,VersionID,ProjectVersion,WorkRole,PlanOrig,VersionStatus) values ('mi.dev.001', 19716,'1.1','Тестировщик', 1570.00,'Planned');

commit;

commit;
