package ru.lb.cppo.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SettingsFormDesign extends CssLayout{
    protected TextField projectName;
    public SettingsFormDesign(){
        Design.read(this);
    }
}
