@startuml
start
 partition инициализация {
    :проверить наличие данных в таблицах PG;
 if (данные есть) then ( да )
    :сформировать запрос на выгрузку данных;
    :создать иниц. таблицы в MySQL;
    :заполнить иниц. таблицы в MySQL;
 else ( нет )
  :выполнить инициализирующий запрос;
 endif
 }

partition "подготовка данных" {
    :сформировать запрос списка проектов;
    :определить дату отсечения заявок;
    :вставить список проектов и дату отсечения в скрипт;
    :выполнить скрипт расчета данных;
    :загрузить данные в таблица PG;
}

partition "загрузка справочников" {
    :рассчитать корректировку справочников;
    :загрузить справочники в PG;
}

end
@enduml